import Head from 'next/head';
import {Inter} from 'next/font/google';
import Image from "next/image";

import styles from '../styles/Home.module.css';
import Banner from "../components/banner";
import Card from "../components/card";
import coffeeStores from '../data/coffee-stores.json';


const inter = Inter({subsets: ['latin']});


export async function getStaticProps(context) {
    return {
        props: {
            coffeeStores,
        }
    }
}


export default function Home(props) {
    console.log(props);


    const handleOnBannerButtonClick = () => {

    }


    return (
        <>
            <Head>
                <title>Coffee shops</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={`${styles.main} ${inter.className}`}>
                <Banner
                    buttonText={'View stores nearby'}
                    handleOnClick={handleOnBannerButtonClick}
                />
                <div className={styles.heroImage}>
                    <Image
                        src="/static/hero-image.png"
                        width={700}
                        height={400}
                        alt="hero image"
                    />
                </div>

                <div className={styles.cardLayout}>
                    {
                        props.coffeeStores
                            .map((coffeeStore) => <Card
                                key={coffeeStore.id}
                                name={coffeeStore.name}
                                imgUrl={coffeeStore.imgUrl}
                                href={`/coffee-store/${coffeeStore.id}`}
                            />)
                    }
                </div>
            </main>
        </>
    )
}
